### ISSUE TITLE
The last instruction in the method is truncated

### ISSUE THREAD

**Issue by rover12421** [rover12421/ShakaApktool#10]
testapk:
原始apk
http://pan.baidu.com/s/1dDB4hjz
加固apk
http://pan.baidu.com/s/1bntXlYv

---

加固apk异常:
```
Error occurred while disassembling class Lcn.com.fmsh.cube.a.a; - skipping class
org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
	at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:87)
	at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:1)
	at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:300)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:691)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226)
	at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:86)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
	at org.jf.baksmali.baksmali.access$0(baksmali.java:177)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Error while processing method Lcn/com/fmsh/cube/a/a;->a()Lcn/com/fmsh/cube/a/a;
```

---

`Lcn.com.fmsh.cube.a.a;`在原始包存在,须正常解析出来

**Comment by rover12421** [comment]
加固包实用了运行时解码,无法静态处理
