### ISSUE TITLE
error: invalid symbol

### ISSUE THREAD

**Issue by pwelyn** [rover12421/ShakaApktool#13]
样本：http://pan.baidu.com/s/1bnhMoiV

错误日志：Exception in thread "main" com.rover12421.shaka.apktool.util.ShakaException: /Users/pwelyn/Downloads/10000000/res/values/public.xml:232: error: invalid symbol: 'do'

/Users/pwelyn/Downloads/10000000/res/values/public.xml:408: error: invalid symbol: 'if'

/Users/pwelyn/Downloads/10000000/res/values/public.xml:1664: error: invalid symbol: 'do'

/Users/pwelyn/Downloads/10000000/res/values/public.xml:1893: error: invalid symbol: 'if'

/Users/pwelyn/Downloads/10000000/res/values/public.xml:2418: error: invalid symbol: 'do'

/Users/pwelyn/Downloads/10000000/res/values/public.xml:2597: error: invalid symbol: 'if'

/Users/pwelyn/Downloads/10000000/res/values/public.xml:5233: error: invalid symbol: 'do'

/Users/pwelyn/Downloads/10000000/res/values/public.xml:5414: error: invalid symbol: 'if'

/Users/pwelyn/Downloads/10000000/res/values/public.xml:7384: error: invalid symbol: 'do'

/Users/pwelyn/Downloads/10000000/res/layout/a8.xml:7: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/qqmarket_push_tips_content_area').

/Users/pwelyn/Downloads/10000000/res/layout/a9.xml:7: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/qqmarket_push_tips_content_area').

/Users/pwelyn/Downloads/10000000/res/layout/a_.xml:7: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/qqmarket_push_tips_content_area').

/Users/pwelyn/Downloads/10000000/res/layout/aa.xml:7: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/qqmarket_push_tips_content_area').

/Users/pwelyn/Downloads/10000000/res/layout/ab.xml:6: error: Error: No resource found that matches the given name (at 'layout' with value '@layout/qqmarket_push_tips_content_area').

/Users/pwelyn/Downloads/10000000/res/layout/ah.xml:2: error: Error: Dimension types not allowed (at 'nestedScrollingEnabled' with value '64.0dip').

/Users/pwelyn/Downloads/10000000/res/layout/ah.xml:2: error: Error: Dimension types not allowed (at 'windowEnterTransition' with value '64.0dip').

/Users/pwelyn/Downloads/10000000/res/layout/ai.xml:2: error: Error: Dimension types not allowed (at 'nestedScrollingEnabled' with value '64.0dip').

/Users/pwelyn/Downloads/10000000/res/layout/ai.xml:2: error: Error: Dimension types not allowed (at 'windowEnterTransition' with value '64.0dip').

/Users/pwelyn/Downloads/10000000/res/layout/aj.xml:2: error: Error: Dimension types not allowed (at 'nestedScrollingEnabled' with value '64.0dip').

/Users/pwelyn/Downloads/10000000/res/layout/aj.xml:2: error: Error: Dimension types not allowed (at 'windowEnterTransition' with value '64.0dip').

	at com.rover12421.shaka.apktool.AspjectJ.apktool_lib.AndrolibResourcesAj.aaptPackage_around(AndrolibResourcesAj.java:202)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:294)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:444)
	at brut.androlib.Androlib.buildResources(Androlib.java:396)
	at brut.androlib.Androlib.build(Androlib.java:285)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
	at com.rover12421.shaka.apktool.Main.main(Main.java:12)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/kn/kqnq_f254212gn9b6tp9_fjw0000gn/T/brut_util_Jar_2595807183067115698.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 16, --version-code, 571400, --version-name, 5.7.2.1400, -F, /var/folders/kn/kqnq_f254212gn9b6tp9_fjw0000gn/T/APKTOOL9099692860656676522.tmp, -I, /Users/pwelyn/Library/apktool/framework/1.apk, -S, /Users/pwelyn/Downloads/10000000/res, -M, /Users/pwelyn/Downloads/10000000/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage_aroundBody28(AndrolibResources.java:419)
	at brut.androlib.res.AndrolibResources$AjcClosure29.run(AndrolibResources.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:221)
	at com.rover12421.shaka.apktool.AspjectJ.apktool_lib.AndrolibResourcesAj.aaptPackage_around(AndrolibResourcesAj.java:73)
	... 8 more
Caused by: brut.common.BrutException: could not exec command: [/var/folders/kn/kqnq_f254212gn9b6tp9_fjw0000gn/T/brut_util_Jar_2595807183067115698.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 16, --version-code, 571400, --version-name, 5.7.2.1400, -F, /var/folders/kn/kqnq_f254212gn9b6tp9_fjw0000gn/T/APKTOOL9099692860656676522.tmp, -I, /Users/pwelyn/Library/apktool/framework/1.apk, -S, /Users/pwelyn/Downloads/10000000/res, -M, /Users/pwelyn/Downloads/10000000/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage_aroundBody28(AndrolibResources.java:413)
	... 11 more

**Comment by rover12421** [comment]
需要使用`-xn`参数才能完全无错回编

**Comment by coiby** [comment]
我从百度网盘下载 [ShakaApktool_2.0.0-master-e5caec2-20150924-release.jar](http://pan.baidu.com/s/1hqpcJNu#path=%252FShakaApktool)，用这里的样本，执行`java -jar ShakaApktool.jar b  10000000 -xn`，还是提示类似的错误：

```
Exception in thread "main" com.rover12421.shaka.b.l: /home/coiby/Downloads/apk/qqbrowser/10000000/res/layout/ah.xml:2: error: Error: Dimension types not allowed (at 'nestedScrollingEnabled' with value '64.0dip').

/home/coiby/Downloads/apk/qqbrowser/10000000/res/layout/ah.xml:2: error: Error: Dimension types not allowed (at 'windowEnterTransition' with value '64.0dip').

/home/coiby/Downloads/apk/qqbrowser/10000000/res/layout/ai.xml:2: error: Error: Dimension types not allowed (at 'nestedScrollingEnabled' with value '64.0dip').

/home/coiby/Downloads/apk/qqbrowser/10000000/res/layout/ai.xml:2: error: Error: Dimension types not allowed (at 'windowEnterTransition' with value '64.0dip').

/home/coiby/Downloads/apk/qqbrowser/10000000/res/layout/aj.xml:2: error: Error: Dimension types not allowed (at 'nestedScrollingEnabled' with value '64.0dip').

/home/coiby/Downloads/apk/qqbrowser/10000000/res/layout/aj.xml:2: error: Error: Dimension types not allowed (at 'windowEnterTransition' with value '64.0dip').


	at b.a.d.a.a(Unknown Source)
	at b.a.d.a.a(Unknown Source)
	at b.a.a.b(Unknown Source)
	at b.a.a.a(Unknown Source)
	at b.a.a.e(Unknown Source)
	at b.a.a.a(Unknown Source)
	at b.b.a.b(Unknown Source)
	at b.b.a.a(Unknown Source)
```
