### ISSUE TITLE
新版本回编译使用问题

### ISSUE THREAD

**Issue by pwelyn** [rover12421/ShakaApktool#20]
Mac和win8 使用release编译的jar回编译会有以下错误信息输出：
I: 正在编译资源...
I: Can't set aapt binary as executable
Exception in thread "main" com.rover12421.shaka.b.l: 
	at com.rover12421.shaka.a.b.e.a(Unknown Source)
	at b.a.d.a.a(Unknown Source)
	at b.a.a.b(Unknown Source)
	at b.a.a.a(Unknown Source)
	at b.a.a.e(Unknown Source)
	at b.a.a.a(Unknown Source)
	at b.b.a.b(Unknown Source)
	at b.b.a.a(Unknown Source)
	at com.rover12421.shaka.cli.Main.main(Unknown Source)
Caused by: com.rover12421.shaka.b.l: Can't set aapt binary as executable
	at b.a.d.a.a(Unknown Source)
	at b.a.d.a.d(Unknown Source)
	at b.a.d.a.a(Unknown Source)
	at b.a.d.l.a(Unknown Source)
	at org.c.b.b.c.a(Unknown Source)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.b.a.b.b.a(Unknown Source)
	at org.b.a.b.b.b(Unknown Source)
	at org.b.a.b.b.a(Unknown Source)
	at com.rover12421.shaka.b.f.a(Unknown Source)
	at com.rover12421.shaka.b.j.a(Unknown Source)
	at com.rover12421.shaka.b.j.c(Unknown Source)
	at com.rover12421.shaka.b.j.a(Unknown Source)
	... 14 more

使用非release编译的jar回编译会输出以下错误：
I: 正在编译资源...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.io.FileNotFoundException: /var/folders/kn/kqnq_f254212gn9b6tp9_fjw0000gn/T/APKTOOL2944564516219863031.tmp (No such file or directory)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	at brut.androlib.Androlib.buildResources(Androlib.java:397)
	at brut.androlib.Androlib.build(Androlib.java:285)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
	at com.rover12421.shaka.cli.Main.main(Main.java:96)
Caused by: brut.directory.DirectoryException: java.io.FileNotFoundException: /var/folders/kn/kqnq_f254212gn9b6tp9_fjw0000gn/T/APKTOOL2944564516219863031.tmp (No such file or directory)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:449)
	... 6 more
Caused by: java.io.FileNotFoundException: /var/folders/kn/kqnq_f254212gn9b6tp9_fjw0000gn/T/APKTOOL2944564516219863031.tmp (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 9 more

**Comment by pwelyn** [comment]
win8.1抛出的错误
I: 正在编译资源...
Exception in thread "main" com.rover12421.shaka.lib.ShakaException:
        at com.rover12421.shaka.apktool.lib.AndrolibResourcesAj.aaptPackage_arou
nd(AndrolibResourcesAj.java:230)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:294)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
        at brut.androlib.Androlib.buildResources(Androlib.java:397)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
        at com.rover12421.shaka.cli.Main.main(Main.java:96)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Users\pwe1yn\ShakaApktool\windows 8.1-x86_64\bin\aapt, p, --f
orced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 21, --version
-code, 64, --version-name, 3.3.4, -F, C:\Users\pwe1yn\AppData\Local\Temp\APKTOOL
8388289268748494006.tmp, -0, arsc, -I, C:\Users\pwe1yn\apktool\framework\1.apk,
-S, C:\Users\pwe1yn\Desktop\Samsung-Phone-INFO+v3.3.4\res, -M, C:\Users\pwe1yn\D
esktop\Samsung-Phone-INFO+v3.3.4\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage_aroundBody28(Androlib
Resources.java:419)
        at brut.androlib.res.AndrolibResources$AjcClosure29.run(AndrolibResource
s.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:
221)
        at com.rover12421.shaka.apktool.lib.AndrolibResourcesAj.aaptPackage_arou
nd(AndrolibResourcesAj.java:101)
        ... 8 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\pwe1yn\S
hakaApktool\windows 8.1-x86_64\bin\aapt, p, --forced-package-id, 127, --min-sdk-
version, 7, --target-sdk-version, 21, --version-code, 64, --version-name, 3.3.4,
 -F, C:\Users\pwe1yn\AppData\Local\Temp\APKTOOL8388289268748494006.tmp, -0, arsc
, -I, C:\Users\pwe1yn\apktool\framework\1.apk, -S, C:\Users\pwe1yn\Desktop\Samsu
ng-Phone-INFO+v3.3.4\res, -M, C:\Users\pwe1yn\Desktop\Samsung-Phone-INFO+v3.3.4\
AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:93)
        at brut.androlib.res.AndrolibResources.aaptPackage_aroundBody28(Androlib
Resources.java:413)
        ... 11 more
Caused by: java.io.IOException: Cannot run program "C:\Users\pwe1yn\ShakaApktool
\windows 8.1-x86_64\bin\aapt": CreateProcess error=193, %1 不是有效的 Win32 应用
程序。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at brut.util.OS.exec(OS.java:84)
        ... 12 more
Caused by: java.io.IOException: CreateProcess error=193, %1 不是有效的 Win32 应
用程序。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 16 more
