### ISSUE TITLE
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000001

### ISSUE THREAD

**Issue by rover12421** [rover12421/ShakaApktool#21]
I: Using ShakaApktool 2.0.0-master-89f2344-20150724
I: Using Apktool 2.0.1-SNAPSHOT-master-f49335a on 淘宝推送.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
	at com.rover12421.shaka.cli.Main.main(Main.java:96)
	at com.rover12421.shaka.test.TestApk.main(TestApk.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000001
	at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:75)
	at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:73)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:73)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 15 more

**Comment by rover12421** [comment]
apk:http://pan.baidu.com/s/1gdiz5hL

**Comment by rover12421** [comment]
引发错误原理:
先查看源码:http://osxr.org/android/source/frameworks/base/libs/androidfw/ResourceTypes.cpp#2804
```cpp
const ResChunk_header* chunk =
        (const ResChunk_header*)(((const uint8_t*)header->header)
                                 + dtohs(header->header->header.headerSize));
    while (((const uint8_t*)chunk) <= (header->dataEnd-sizeof(ResChunk_header)) &&
           ((const uint8_t*)chunk) <= (header->dataEnd-dtohl(chunk->size))) {
        status_t err = validate_chunk(chunk, sizeof(ResChunk_header), header->dataEnd, "ResTable");
```
用hex编辑器查看这个apk的arsc文件,会发现他的ResChunk_header中的headerSize是20,标准的arsc文件第一个结构是ResTable_header,ResTable_header实际大小是12,也就是headerSize=12,但这个apk修改了headerSize,改为了20.但是android是不会报错的,因为android是加上这个headerSize偏移再继续读取后面的数据.
再来看apktool读取:
```java
private ResPackage[] readTable() throws IOException, AndrolibException {
        nextChunkCheckType(Header.TYPE_TABLE);
        int packageCount = mIn.readInt();

        mTableStrings = StringBlock.read(mIn);
        ResPackage[] packages = new ResPackage[packageCount];

        nextChunk();
        for (int i = 0; i < packageCount; i++) {
            packages[i] = readPackage();
        }
        return packages;
    }

private void nextChunkCheckType(int expectedType) throws IOException,
            AndrolibException {
        nextChunk();
        checkChunkType(expectedType);
    }

private Header nextChunk() throws IOException {
        return mHeader = Header.read(mIn);
    }

public static Header read(ExtDataInput in) throws IOException {
            short type;
            try {
                type = in.readShort();
            } catch (EOFException ex) {
                return new Header(TYPE_NONE, 0);
            }
            in.skipBytes(2);
            return new Header(type, in.readInt());
        }
```

不得不说,要修复这个bug,而又不直接改源码是非常辣手的问题.
