### ISSUE TITLE
Rename ResResSpec windowTitleStyle to android:windowTitleStyle

### ISSUE THREAD

**Issue by Ezalor** [rover12421/ShakaApktool#25]
最近在编译一些apk的时候会出现这个：
Rename ResResSpec windowTitleStyle to android:windowTitleStyle

I: 正在加载资源列表...
I: 反编译 AndroidManifest.xml 与资源...
I: 正在从框架文件加载资源列表: /home/lwb/apktool/framework/1.apk
I: 常规资源列表...
I: 反编译资源文件...
W: Rename ResResSpec windowTitleStyle to android:windowTitleStyle
I: 反编译 values */* XMLs...
I: Re 反编译资源文件...
I: 反编译 classes.dex...
I: 复制 assets 和 libs...
I: 复制未知文件...
I: 复制原始文件...

好奇怪，然后回编译就会报错

I: 检查是否有被修改的代码...
I: 编译 smali 到 classes.dex...
I: 检查是否有被修改的资源...
I: 正在编译资源...
Exception in thread "main" com.rover12421.shaka.b.l: /home/lwb/下载/AppMgr/res/values/styles.xml:717: error: Error: No resource found that matches the given name: attr 'android:android:windowTitleStyle'.

/home/lwb/下载/AppMgr/res/values/styles.xml:838: error: Error: No resource found that matches the given name: attr 'android:android:windowTitleStyle'.

/home/lwb/下载/AppMgr/res/values/styles.xml:1362: error: Error: No resource found that matches the given name: attr 'android:android:windowTitleStyle'.

/home/lwb/下载/AppMgr/res/values/styles.xml:1370: error: Error: No resource found that matches the given name: attr 'android:android:windowTitleStyle'.

	at com.rover12421.shaka.a.b.g.a(Unknown Source)
	at b.a.d.a.a(Unknown Source)
	at b.a.a.b(Unknown Source)
	at b.a.a.a(Unknown Source)
	at b.a.a.e(Unknown Source)
	at b.a.a.a(Unknown Source)
	at b.b.a.b(Unknown Source)
	at b.b.a.a(Unknown Source)
	at com.rover12421.shaka.cli.Main.main(Unknown Source)
Caused by: b.a.D: b.c.a: could not exec command: [/home/lwb/ShakaApktool/linux-x86/bin/aapt, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 15, --version-code, 90003659, --version-name, 3.65, -F, /tmp/APKTOOL7140205780916340015.tmp, -0, resources.arsc, -0, arsc, -I, /home/lwb/apktool/framework/1.apk, -S, /home/lwb/下载/AppMgr/res, -M, /home/lwb/下载/AppMgr/AndroidManifest.xml]
	at b.a.d.a.a(Unknown Source)
	at b.a.d.l.a(Unknown Source)
	at org.c.b.b.c.a(Unknown Source)
	... 9 more
Caused by: b.c.a: could not exec command: [/home/lwb/ShakaApktool/linux-x86/bin/aapt, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 15, --version-code, 90003659, --version-name, 3.65, -F, /tmp/APKTOOL7140205780916340015.tmp, -0, resources.arsc, -0, arsc, -I, /home/lwb/apktool/framework/1.apk, -S, /home/lwb/下载/AppMgr/res, -M, /home/lwb/下载/AppMgr/AndroidManifest.xml]
	at b.e.i.a(Unknown Source)
	... 12 more

麻烦大神看一下哦~谢谢！~

**Comment by Ezalor** [comment]
比如说这一个APK：
http://coolapk.com/apk/com.a0soft.gphone.app2sd.pro

**Comment by pwelyn** [comment]
可以直接将错误的行修改一下
AppMgr/res/values/styles.xml:717 android:android:windowTitleStyle改成android:windowTitleStyle
AppMgr/res/values/styles.xml:838 android:android:windowTitleStyle改成android:windowTitleStyle
AppMgr/res/values/styles.xml:1362 android:android:windowTitleStyle改成android:windowTitleStyle
AppMgr/res/values/styles.xml:1370 android:android:windowTitleStyle改成android:windowTitleStyle
改完只换然后再回编译

**Comment by Ezalor** [comment]
嗯嗯，可以了~~~试了下最新的，已经没有这个问题啦！~~~~~~~~
