### ISSUE TITLE
resource spec ID

### ISSUE THREAD

**Issue by pwelyn** [rover12421/ShakaApktool#34]
经过测试使用HEX打开resources.arsc,查找对drawable或string对应值t=0x03修改为0x01或0x02都可以导致反编译失败出现以下错误日志:
```javascript
ception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x7f000005
  at brut.androlib.res.data.ResPackage.getResSpec_aroundBody0(ResPackage.java:59)
  at brut.androlib.res.data.ResPackage$AjcClosure1.run(ResPackage.java:1)
  at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:221)
  at com.rover12421.shaka.apktool.lib.ResPackageAj.getResSpec(ResPackageAj.java:41)
  at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:56)
  at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
  at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
  at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
  at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
  at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlValue(ResScalarValue.java:58)
  at brut.androlib.res.data.value.ResScalarValue.serializeToResValuesXml(ResScalarValue.java:75)
  at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
  at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
  at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:136)
  at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
  at brut.apktool.Main.cmdDecode(Main.java:165)
  at brut.apktool.Main.main(Main.java:81)
  at com.rover12421.shaka.cli.Main.main(Main.java:95)
```
```
aapt d resources test.apk
Package Groups (1)
Package Group 0 id=0x7f packageCount=1 name=com.example.myapp
  Package 0 id=0x7f name=com.example.myapp
    type 1 configCount=4 entryCount=1
      spec resource 0x7f020000 com.example.myapp:drawable/ic_launcher: flags=0x00000100
      config ldpi-v4:
        resource 0x7f020000 com.example.myapp:drawable/ic_launcher: t=0x03 d=0x00000001 (s=0x0008 r=0x00)
      config mdpi-v4:
        resource 0x7f020000 com.example.myapp:drawable/ic_launcher: t=0x03 d=0x00000002 (s=0x0008 r=0x00)
      config hdpi-v4:
        resource 0x7f020000 com.example.myapp:drawable/ic_launcher: t=0x03 d=0x00000003 (s=0x0008 r=0x00)
      config xhdpi-v4:
        resource 0x7f020000 com.example.myapp:drawable/ic_launcher: t=0x03 d=0x00000004 (s=0x0008 r=0x00)
    type 2 configCount=1 entryCount=1
      spec resource 0x7f030000 com.example.myapp:layout/main: flags=0x00000000
      config (default):
        resource 0x7f030000 com.example.myapp:layout/main: t=0x03 d=0x00000000 (s=0x0008 r=0x00)
    type 3 configCount=1 entryCount=1
      spec resource 0x7f040000 com.example.myapp:string/app_name: flags=0x00000000
      config (default):
        resource 0x7f040000 com.example.myapp:string/app_name: t=0x02 d=0x00000005 (s=0x0008 r=0x00)
```
**t=0x02**或**t=0x01**都会出现上面错误，**t=0x00**或**t=0x03**不会其他值没有测试

测试app地址：http://pan.baidu.com/s/1c0nx0Tq

**Comment by rover12421** [comment]
遇到这样的包,只能执行判断.
针对你的这个样本,添加了简单的字符串资源较真来解决. 可以查看: f235496c950897369f1e3fb58d8be875e525224d

也可以使用 `-ir` 参数来忽略错误.新增加了encodeAsResXml 错误的忽略. e30c8e8d6e10cc76e15edf493f2e1cffb847b20c

也可以使用 `-fui` 来正常反编译,然后手动判断是否纠正或是删除带`FuckUnkownId`的资源,然后回编译

**Comment by Vincent-HaoZ** [comment]
楼主的fuckUnknownId也是醉了😱
