### ISSUE TITLE
java.util.zip.ZipException: STORED entry missing size, compressed size, or crc-32

### ISSUE THREAD

**Issue by pwelyn** [rover12421/ShakaApktool#40]
使用ShakaApktool if三星框架出现的错误
`Exception in thread "main" brut.androlib.AndrolibException: java.util.zip.ZipException: STORED entry missing size, compressed size, or crc-32
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:647)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:592)
	at brut.androlib.Androlib.installFramework(Androlib.java:643)
	at brut.apktool.Main.cmdInstallFramework(Main.java:239)
	at brut.apktool.Main.main(Main.java:87)
	at com.rover12421.shaka.cli.Main.main(Main.java:95)
Caused by: java.util.zip.ZipException: STORED entry missing size, compressed size, or crc-32
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:207)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:639)
	... 5 more`
[附上样本下载](http://pan.baidu.com/s/1slkVmDv)
使用apktool 2.1.1可以正常if

**Comment by rover12421** [comment]
fix https://github.com/iBotPeaches/Apktool/pull/1263
