### ISSUE TITLE
decompile with no-src fail

### ISSUE THREAD

**Issue by F8LEFT** [rover12421/ShakaApktool#46]
In File
shaka/cli/src/main/java/com/rover12421/shaka/cli/apktool/DecodeCommand .line 177
decoder.setDecodeResources(ApkDecoder.DECODE_SOURCES_NONE);

I guess it should be
decoder.setDecodeSource(ApkDecoder.DECODE_SOURCES_NONE);

**Comment by F8LEFT** [comment]
compile failed with java.lang.NullPointerException
This is the error log
Exception in thread "main" com.rover12421.shaka.lib.ShakaException:
	at brut.androlib.res.AndrolibResources.aaptPackage_aroundBody29$advice(AndrolibResources.java:400)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:1)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
	at brut.androlib.Androlib.buildResources(Androlib.java:427)
	at brut.androlib.Androlib.build(Androlib.java:326)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at com.rover12421.shaka.cli.apktool.BuildCommand.run(BuildCommand.java:87)
	at com.rover12421.shaka.cli.Main.main(Main.java:156)
Caused by: java.lang.NullPointerException
	at brut.androlib.res.AndrolibResources.aaptPackage_aroundBody28(AndrolibResources.java:318)
	at brut.androlib.res.AndrolibResources.aaptPackage_aroundBody29$advice(AndrolibResources.java:361)
	... 7 more

I found apkOptions.aaptPath is null...
maybe this can be fix in BuildCommand.java .line 79
if(aaptPath != null) {
     apkOptions.aaptPath = aaptPath;
}
