### ISSUE TITLE
回编译出错 (19448): First type is not attr!

### ISSUE THREAD

**Issue by xqyphp** [rover12421/ShakaApktool#50]
W: Found exception png file : D:\tmp\out\res\drawable-tvdpi\common_plus_signin_btn_icon_dark_pressed.9.png
Exception in thread "main" com.rover12421.shaka.b.l: W: A/        (19448): First type is not attr!
W: 
W: This application has requested the Runtime to terminate it in an unusual way.
W: Please contact the application's support team for more information.

	at b.a.d.a.a(Unknown Source)
	at b.a.d.a.a(Unknown Source)
	at b.a.a.a(Unknown Source)
	at b.a.a.a(Unknown Source)
	at b.a.a.e(Unknown Source)
	at b.a.a.a(Unknown Source)
	at b.b.a.b(Unknown Source)
	at b.b.a.a(Unknown Source)
	at com.rover12421.shaka.cli.Main.main(Unknown Source)
Caused by: b.a.A: b.c.a: could not exec (exit code = 3): [C:\Users\likai_m\ShakaApktool\windows-x86\bin\aapt.exe, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 22, --version-code, 5, --version-name, 1.28.0, -F, C:\Users\likai_m\AppData\Local\Temp\APKTOOL3204273891692388115.tmp, -0, arsc, -I, C:\Users\likai_m\AppData\Local\apktool\framework\1.apk, -S, D:\tmp\out\res, -M, D:\tmp\out\AndroidManifest.xml]
	at b.a.d.a.a(Unknown Source)
	... 11 more
Caused by: b.c.a: could not exec (exit code = 3): [C:\Users\likai_m\ShakaApktool\windows-x86\bin\aapt.exe, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 22, --version-code, 5, --version-name, 1.28.0, -F, C:\Users\likai_m\AppData\Local\Temp\APKTOOL3204273891692388115.tmp, -0, arsc, -I, C:\Users\likai_m\AppData\Local\apktool\framework\1.apk, -S, D:\tmp\out\res, -M, D:\tmp\out\AndroidManifest.xml]
	at b.e.i.a(Unknown Source)
	... 12 more

**Comment by wufeng0927** [comment]
gradle build tools的版本太高，改成2.2.3试试 。

**Comment by xqyphp** [comment]
嗯，谢谢啦。比较久了，有空我找找试试

**Comment by ingbrzy** [comment]
@rover12421 can you build aapt2 with your mods..?
